### ISSUE TITLE
안녕하세요. 해당 번역본의 원작자입니다.

### ISSUE THREAD

**Issue by minwook-shin** [sebuls/q2aKorea#1]
안녕하세요. Q2A KOREA 번역자 @minwook-shin 입니다.
먼저 말씀드리고싶은것은 비록 [과거 사이가 않좋았어도](https://forum.ubuntu-kr.org/viewtopic.php?f=2&t=28322) 
세벌님께서 제 Q2A 번역을 사용하시는것은 막지 않습니다만,
세벌님의 레포에 문제가 있어서 부득이하게 이슈를 작성하게 되었습니다... 
아래 문제점을 시정해주시거나 의견을 남겨주시면 상황에 따라서 대처하겠습니다.
#1. 라이선스파일이 없습니다.

현재 Question2Answer측의 라이선스는 GPL2.0 아래에 있습니다.
http://www.question2answer.org/license.php
그리하여 세벌님께서 가져가신 **제 번역본 역시 GPL2.0입니다**
아시다시피 GPL은 전염성 조항이 있어서 일부라도 포함시 라이선스가 GPL로 되고,
이와 같이 거의 전부를 가져오신 경우에도 당연히 GPL입니다.
그러니, 제 번역본에 있는 파일 **그대로**
https://github.com/minwook-shin/q2a-korean-translation/blob/master/LICENSE
위 라이선스 파일을 레포에 업로드해주세요.

그리고 README 파일은 특별히 제약없습니다.
#2. 가급적이면 포크가 어떨까요?

오픈소스에서는 서로 돕고 돕는게 맞습니다.
README에서 "틈틈이 다듬고 있습니다." 라고 하시는걸 보니 꽤 수정한걸로 보입니다만,
제가 어딜 다듬었고 어딜 삭제했는지 어떻게 알고 협력합니까...
**깃허브에는 FORK와 PULL REQUEST라는 좋은 시스템**이 있으니 이걸 활용해보세요.
포크하신뒤에 본인 저장소에서 수정하시고 pull request를 저에게 보내면 바로 컨펌이됩니다.
#3. 커밋 기록을 남겨주세요.

부득이하게 직접 레포를 운영하시겠더라도 커밋 기록이 전부 생성,삭제뿐이니
무엇을 어디에 어떻게 바꾸었는지 위와같이 알수 없습니다.
이것은 저 뿐만이 아니라 추후에 번역팩 사용자가 번역에 관한 문제를 제기할때
누가 수정했는지 바로 알수없으므로  그 제3의 인물과 저와 세벌님께 많은 피로를 주게됩니다.
그러니, **커밋 기록을 최소한 어느 부분을 수정했는지 써주시길 바랍니다**.
#4.세벌님의 이 저장소의 위키에 오해의 소지가 있습니다.

https://github.com/sebuls/q2aKorea/wiki
"한국어가 없길래 시작합니다." "한국어 번역은 제가 대충 했습니다." 등은
추후 오해가 쌓이기 충분합니다.
위키를 수정하시거나 삭제해주시기바랍니다.
# 마무리

위의 사항을 빠른 시일안에 고쳐주시기바랍니다.

**Comment by sebuls** [comment]
안녕하셔요. 신민욱님이셨군요. 혹시 http://www.masterqna.com/android/ 원작자님과는 연락하고 지내시나요?
그분과 소통하시면 더 좋은 작품나올것 같습니다. 제가 만들어놓은건 연습삼아 만든거니 너무 신경쓰지 않으셔도 되어요. 위키는 아무나
건드릴수있으니 안 맞는 부분은 님께서 손보셔도 됩니다.

스마트폰이라서 글쓰기가 쉽지않네요.
2016. 2. 18. 16:27에 "minwook shin" notifications@github.com님이 작성:

**Comment by sebuls** [comment]
않좋았어도? 오타겠죠? 안 좋았어도가 맞는 표현이겠죠. 좋고 안 좋고 할 일도 없습니다만.

님의 글을 보고 제 저장소에 LICENSE 파일 만들었습니다.

한국어 없길래 번역 시작한 건 저 맞고요. 다른 사람이 먼저 시작했는데 제가 모르고 있었을 수도... 공식사이트에 님의 번역이 들어갔다고 님께서 번역을 저보다 먼저 시작했다고 하고 싶은 건가요? 어차피 위키는 저말고 다른 사람들도 건드릴 수 있으니 님께서 잘 다듬어 주셔요.

커밋 기록은 지난 건 할 수 없고 앞으로는 남기겠습니다.

**Comment by minwook-shin** [comment]
라이선스를 추가 해주셨군요! 그리고 커밋기록도 앞으로 작성해주신다니, 정말 감사합니다.
그런데... 나머지 항목은 의미 전달이 이상해진거 같습니다.

먼저 세벌님께서 먼저 번역하셨다는 소식은 저도 q2a 번역 준비하다가 공식 웹사이트에서 알게되었습니다.
http://www.question2answer.org/qa/32886/i-made-korean-translations
무려 2014년 5월 19일에 하셨다는것에 놀라움을 감추지못했습니다만
세벌님께선 q2a 버전이 1.6.x인것을 번역하신거였고,  현제 최신버전인 1.7.x는 아니였습니다...

그런 상황에 제가 작년 5월즈음 깃허브에 레포를 검색해보았으나 관련 레포가 없었음을 확인 후
1.7.x버전대의 번역팩의 번역을 시작했고, 작년 5월 23일에 깃허브 업로드와 함께 초벌 번역이되었습니다.
그리고 몇일 후 공식 번역으로 공식 홈페이지에 링크되었고 우분투 한국 커뮤니티 ask에도 번역팩이 쓰였습니다.

만약 번역을 세벌님보다 먼저했다고 바랬으면 1.6.x 버전대를 먼저 작업하고 1.7.x 버전으로 넘어갔을껍니다.
하지만 저는 1.6.x는 세벌님의 작업물이란것을 계속 인지하였기에 그당시 번역이 없었던 1.7.x버전만 작업했습니다... 
전 번역이 없는걸 만들어서 배포했을 뿐인데.... 다 번역하고나서 이렇게 다시 돌아오니...기분이 좀 그렇네요.

마지막으로 정리하자면...
세벌님께서 번역이 조금하셨더라도 **먼저 번역 하신 1.6.x버전대의 번역 작업물에 대해선 존중**해드리며(삭제 후 전문을 **그냥** 가져가시기전에는 아무런 언급도 하지않았습니다),
또한 본 이슈에서의 위키 수정 혹은삭제를 언급한것은 **오직 공식 번역본 가져가신 이후에만** 오해의 소지가 있다는걸 말씀드립니다.

**Comment by sebuls** [comment]
서로간에 오해가 있었군요. 위키 좀 수정했는데 잘못된 부분 있으면 님께서 다듬어 주셔요.
