### ISSUE TITLE
위키 내용이 이상합니다.

### ISSUE THREAD

**Issue by ghost** [sebuls/q2aKorea#2]
위키 문서에는 프로젝트에 대한 설명이 있어야 하는 것이 상식인데...
내용을 읽어보면, `한국어 번역 제가 했습니다`, `최초 번역자는 누구일까?` 등의 이상한 내용이 있습니다.
해당 문구를 삭제하시고 프로젝트에 대한 설명을 넣어주시기 바랍니다.
또한, `http://www.masterqna.com/android/ 번역이 잘 되어 있는데 이것을 번역하신 분을 못 찾고 있습니다.` 라고 하셨는데,

http://www.masterqna.com/android/feedback 에 문의하시기 바랍니다.
참고로 번역물에 대해서도 저작권이라는 것이 있습니다.

**Comment by sebuls** [comment]
위키는 다른 사람도 수정할 수 있으니 잘못된 내용이 있으면 바로잡아주시면 됩니다.
http://www.masterqna.com/android/ 쪽에는 한참 전에 물어 보았는데 응답이 없네요.

**Comment by ghost** [comment]
오밤중이니 주무시고 계시겠죠.
