### ISSUE TITLE
관리자 페이지만 영문으로 나타나게 하려면?

### ISSUE THREAD

**Issue by ghost** [sebuls/q2aKorea#3]
일반 사용자가 보는 화면은 한국어 번역이 나타나고, 관리자 페이지로 들어가면 한국어 번역 대신 영어 원본 그대로 나타나게 하려면 어떻게 하나요?

**Comment by ghost** [comment]
https://github.com/minwook-shin/q2a-korean-translation/issues/17

**Comment by sebuls** [comment]
제가 질문하고 제가 답을 찾았네요.

http://sebul.sarang.net/q2a-kr/translate.html 에
특정 구를 US English로 놔두려면, 파일에서 그 행을 지워도 된다. qa-lang-admin.php와 qa-lang-options.php파일을 없애는 것을 선택할 수도 있다 - 이 파일들은 admin interface 에서만 쓰고 Q2A의 보통 사용자가 볼 수 있는 구는 포함하지 않는다.
고 제가 번역해 놓고 잊고 있었네요.

qa-lang/ko/ 디렉토리에서 qa-lang-admin.php 와 qa-lang-options.php 이 두 개 파일을 지우면 되네요.
