### ISSUE TITLE
README 내용이 이상합니다.

### ISSUE THREAD

**Issue by ghost** [sebuls/q2aKorea#4]
*.php 파일들을 보니
https://github.com/minwook-shin/q2a-korean-translation 여기에 있는 것을 전부 가져오신 것 같은데..
REAMDE 파일도 이에 맞게 변경해야죠.
라이선스에 대한 문제는 없는 것 같은데, 기본적인 예의는 지키셨으면 좋겠습니다.
이러한 행위는 협업을 하자는 것이 아니라 훼방놓는 행위로 보입니다.
그리고 README 영문 파일 제공 바랍니다.

**Comment by sebuls** [comment]
그곳에 있는 것 가져왔다는 걸 숨기려고 했다면 제가 주석을 살짝 지웠겠지요.
훼방 아닙니다. 오해 없으시길.
한국어 번역판인데 readme 영문파일을 반드시 제공해야 하나요?
꼭 해야 한다면 readme 영문파일에 뭐라고 쓰면 되는지 알려주셔요.

**Comment by ghost** [comment]
>  꼭 해야 한다면 readme 영문파일에 뭐라고 쓰면 되는지 알려주셔요.
> README 파일에 있는 한국어를 영어로 번역하여 작성해야죠.

그리고 README 파일 내용은 오해의 소지가 큽니다.
신민욱 님이 번역하신 건데, README 파일 내용을 보면 세벌 님이 번역하신 걸로 오해할 소지가 농후합니다.
신민욱 님을 괴롭힐 목적이 없다면 하루 속히 수정되기를 바랍니다.

**Comment by sebuls** [comment]
cogniti 님이 신민욱 님의 대변인인가요?
README 파일 다시 읽어 봤습니다.
다른 분이 번역한 것과 제가 한 것을 보면서 틈틈이 다듬고 있습니다.
를 보고 저 혼자서 번역한 걸로 생각하시면 곤란하지요.
한국어 번역본은 기본적으로 한국인(또는 한국인이 아니라도 한국어를 이해하는 사람)을 위한 것이라고 생각합니다.
한국어 번역본 README 파일 내용을 굳이 영어로 할 까닭은 없다고 생각합니다.

**Comment by ghost** [comment]
세벌님은 이미 과거에도 이와 유사한 문제를 일으킨 적이 있습니다.

http://www.ktug.org/xe/index.php?document_srl=205830&mid=KTUG_open_board

http://www.ktug.org/xe/index.php?document_srl=205605&mid=KTUG_QnA_board

제 판단도 마찬가지인데... 신민욱 님이 작업하신 것을 github 에서 작업하실 것이 아니라 오로지 개인 컴퓨터에서 비공개로 개인적으로 작업하시는 것이 좋겠습니다.
그리고 세벌님이 번역한 부분이 없습니다. 신민욱 님의 번역물이죠.

**Comment by sebuls** [comment]
다른 사이트에서의 일을 여기 끌어들이지 않으시길 바랍니다.

번역물 차이를 보려면 diff 명령어를 쓰면 됩니다.

**Comment by ghost** [comment]
로그를 남기지 않으셨길래 세벌님 번역분이 없는 줄 알았습니다. 정정합니다.
파일을 각각 다운 받아서 확인해보니 유저를 사용자로 수정한 것 같습니다.
git 기능을 숙지하셔서 수정 로그를 남기셨으면 좋겠습니다.

**Comment by sebuls** [comment]
git 기능을 익히고 있음. 수정 로그 남기고 있음.
